const ADD = 'PRODUCT_ADD';
const COMPARE = 'PRODUCT_COMPARE';
const ORDER = 'PRODUCT_ORDER';
const REMOVE = 'PRODUCT_REMOVE';
const INC = 'PRODUCT_INC';
const DEC = 'PRODUCT_DEC';

export { ADD,COMPARE,ORDER,REMOVE,INC,DEC };
