const ADD = 'PRODUCT_ADD';
const COMPARE = 'PRODUCT_COMPARE';
const ORDER = 'PRODUCT_ORDER';
const INCREASE = 'PRODUCT_INCREASE';
const DECREASE = 'PRODUCT_DECREASE';

export { ADD, ORDER, COMPARE, INCREASE, DECREASE };
